export const LOGIN_UPDATE = 'LOGIN_UPDATE';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_UPDATE = 'REGISTER_UPDATE';
export const SIGNIN = 'SIGNIN';
export const SIGNINSUCCESS = 'SIGNINSUCCESS';
export const SIGNINFAILED = 'SIGNINFAILED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GENERATE_OTP = 'GENERATE_OTP';
export const GENERATE_OTP_SUCCESS = 'GENERATE_OTP_SUCCESS';
export const GENERATE_OTP_FAILED = 'GENERATE_OTP_FAILED';
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const GET_STORES = 'GET_STORES';
export const FETCH_PRODUCT_CATEGORIES = 'FETCH_PRODUCT_CATEGORIES';
export const FETCH_PRODUCT_CATEGORIES_SUCCESS =
  'FETCH_PRODUCT_CATEGORIES_SUCCESS';
export const FETCH_PRODUCT_CATEGORIES_FAILED =
  'FETCH_PRODUCT_CATEGORIES_FAILED';
export const FETCH_STORES_BY_PRODUCT_CATEGORY =
  'FETCH_STORES_BY_PRODUCT_CATEGORY';

export const FETCH_STORES_BY_PRODUCT_CATEGORY_SUCCESS =
  'FETCH_STORES_BY_PRODUCT_CATEGORY_SUCCESS';

export const FETCH_STORES_BY_PRODUCT_CATEGORY_FAILED =
  'FETCH_STORES_BY_PRODUCT_CATEGORY_FAILED';

export const FETCH_PRODUCTS_BY_STORE_ID_SUB_CATEGORY_ID =
  'FETCH_PRODUCTS_BY_STORE_ID_SUB_CATEGORY_ID';

export const FETCH_PRODUCTS_BY_STORE_ID_SUB_CATEGORY_ID_SUCCESS =
  'FETCH_PRODUCTS_BY_STORE_ID_SUB_CATEGORY_ID_SUCCESS';

export const FETCH_PRODUCTS_BY_STORE_ID_SUB_CATEGORY_ID_FAILED =
  'FETCH_PRODUCTS_BY_STORE_ID_SUB_CATEGORY_ID_FAILED';

export const SET_VALUE = 'SET_VALUE';

export const FETCH_PROD_SUB_CATEGORIES_STORE_ID_PROD_ID =
  'FETCH_PRODUCT_SUB_CATEGORIES_BY_STORE_ID_PRODUCT_ID';

export const FETCH_PROD_SUB_CATEGORIES_STORE_ID_PROD_ID_SUCCESS =
  'FETCH_PRODUCT_SUB_CATEGORIES_BY_STORE_ID_PRODUCT_ID_SUCCESS';

export const FETCH_PROD_SUB_CATEGORIES_STORE_ID_PROD_ID_FAILED =
  'FETCH_PRODUCT_SUB_CATEGORIES_BY_STORE_ID_PRODUCT_ID_FAILED';

export const ADD_ITEMS_TO_CART = 'ADD_ITEMS_TO_CART';
export const RESET_CART = 'RESET_CART';
export const PURCHASE = 'PURCHASE';
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS';
export const SAVE_ORDER_FAILED = 'SAVE_ORDER_FAILED';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILED = 'PURCHASE_FAILED';

export const FETCH_PURCHASE_HISTORY_SELLER_WISE =
  'FETCH_PURCHASE_HISTORY_SELLER_WISE';
export const FETCH_PURCHASE_HISTORY_SELLER_WISE_SUCCESS =
  'FETCH_PURCHASE_HISTORY_SELLER_WISE_SUCCESS';
export const FETCH_PURCHASE_HISTORY_SELLER_WISE_FAILED =
  'FETCH_PURCHASE_HISTORY_SELLER_WISE_FAILED';

export const FETCH_PURCHASE_HISTORY_PRODUCT_WISE =
  'FETCH_PURCHASE_HISTORY_PRODUCT_WISE';
export const FETCH_PURCHASE_HISTORY_PRODUCT_WISE_SUCCESS =
  'FETCH_PURCHASE_HISTORY_PRODUCT_WISE_SUCCESS';
export const FETCH_PURCHASE_HISTORY_PRODUCT_WISE_FAILED =
  'FETCH_PURCHASE_HISTORY_PRODUCT_WISE_FAILED';

export const FETCH_PURCHASE_HISTORY = 'FETCH_PURCHASE_HISTORY';
export const FETCH_PURCHASE_HISTORY_SUCCESS = 'FETCH_PURCHASE_HISTORY_SUCCESS';
export const FETCH_PURCHASE_HISTORY_FAILED = 'FETCH_PURCHASE_HISTORY_FAILED';

export const SET_ACCOUNT = 'SET_ACCOUNT';

////////////////////////////////////////////////////////////////
//Seller

export const FETCH_PROD_SUB_CATEGORIES = 'FETCH_PROD_SUB_CATEGORIES';
export const FETCH_PROD_SUB_CATEGORIES_SUCCESS =
  'FETCH_PROD_SUB_CATEGORIES_SUCCESS';
export const FETCH_PROD_SUB_CATEGORIES_FAILED =
  'FETCH_PROD_SUB_CATEGORIES_FAILED';
export const UPDATE_ADD_ITEMS = 'UPDATE_ADD_ITEMS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_FAILED = 'EDIT_PRODUCT_FAILED';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_FAILED = 'REMOVE_PRODUCT_FAILED';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';

export const FETCH_PURCHASE_HISTORY_PRODUCT_WISE_SELLER =
  'FETCH_PURCHASE_HISTORY_PRODUCT_WISE_SELLER';
export const FETCH_PURCHASE_HISTORY_PRODUCT_WISE_SUCCESS_SELLER =
  'FETCH_PURCHASE_HISTORY_PRODUCT_WISE_SUCCESS_SELLER';
export const FETCH_PURCHASE_HISTORY_PRODUCT_WISE_FAILED_SELLER =
  'FETCH_PURCHASE_HISTORY_PRODUCT_WISE_FAILED_SELLER';

export const FETCH_PURCHASE_HISTORY_CLIENT_WISE_SELLER =
  'FETCH_PURCHASE_HISTORY_CLIENT_WISE_SELLER';
export const FETCH_PURCHASE_HISTORY_CLIENT_WISE_SUCCESS_SELLER =
  'FETCH_PURCHASE_HISTORY_CLIENT_WISE_SUCCESS_SELLER';
export const FETCH_PURCHASE_HISTORY_CLIENT_WISE_FAILED_SELLER =
  'FETCH_PURCHASE_HISTORY_CLIENT_WISE_FAILED_SELLER';

export const FETCH_PURCHASE_HISTORY_INVENTORY_WISE_SELLER =
  'FETCH_PURCHASE_HISTORY_INVENTORY_WISE_SELLER';
export const FETCH_PURCHASE_HISTORY_INVENTORY_WISE_SUCCESS_SELLER =
  'FETCH_PURCHASE_HISTORY_INVENTORY_WISE_SUCCESS_SELLER';
export const FETCH_PURCHASE_HISTORY_INVENTORY_WISE_FAILED_SELLER =
  'FETCH_PURCHASE_HISTORY_INVENTORY_WISE_FAILED_SELLER';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';
