export const LOGIN_UPDATE = 'LOGIN_UPDATE';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_UPDATE = 'REGISTER_UPDATE';
export const SIGNIN = 'SIGNIN';
export const SIGNINSUCCESS = 'SIGNINSUCCESS';
export const SIGNINFAILED = 'SIGNINFAILED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GENERATE_OTP = 'GENERATE_OTP';
export const GENERATE_OTP_SUCCESS = 'GENERATE_OTP_SUCCESS';
export const GENERATE_OTP_FAILED = 'GENERATE_OTP_FAILED';
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const GET_STORES = 'GET_STORES';
export const FETCH_PRODUCT_TYPES = 'FETCH_PRODUCT_TYPES';
export const FETCH_PRODUCT_TYPES_SUCCESS = 'FETCH_PRODUCT_TYPES_SUCCESS';
export const FETCH_PRODUCT_TYPES_FAILED = 'FETCH_PRODUCT_TYPES_FAILED';
export const FETCH_STORES_BY_PRODUCT_TYPE = 'FETCH_STORES_BY_PRODUCT_TYPE';

export const FETCH_STORES_BY_PRODUCT_TYPE_SUCCESS =
  'FETCH_STORES_BY_PRODUCT_TYPE_FAILED';

export const FETCH_STORES_BY_PRODUCT_TYPE_FAILED =
  'FETCH_STORES_BY_PRODUCT_TYPE_FAILED';

export const FETCH_PRODUCTS_BY_STORE_ID_SUB_TYPE_ID =
  'FETCH_PRODUCTS_BY_STORE_ID_SUB_TYPE_ID';

export const FETCH_PRODUCTS_BY_STORE_ID_SUB_TYPE_ID_SUCCESS =
  'FETCH_PRODUCTS_BY_STORE_ID_SUB_TYPE_ID_SUCCESS';

export const FETCH_PRODUCTS_BY_STORE_ID_SUB_TYPE_ID_FAILED =
  'FETCH_PRODUCTS_BY_STORE_ID_SUB_TYPE_ID_FAILED';

export const SET_VALUE = 'SET_VALUE';

export const FETCH_PROD_SUB_TYPES_STORE_ID_PROD_ID =
  'FETCH_PRODUCT_SUB_TYPES_BY_STORE_ID_PRODUCT_ID';

export const FETCH_PROD_SUB_TYPES_STORE_ID_PROD_ID_SUCCESS =
  'FETCH_PRODUCT_SUB_TYPES_BY_STORE_ID_PRODUCT_ID_SUCCESS';

export const FETCH_PROD_SUB_TYPES_STORE_ID_PROD_ID_FAILED =
  'FETCH_PRODUCT_SUB_TYPES_BY_STORE_ID_PRODUCT_ID_FAILED';
